services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:80"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      DATABASE_URL: "sqlite+aiosqlite:///./dev_database.db"
    restart: unless-stopped
